name: "release-plz"
author: "Marco Ieni"
description: "Update version and changelog based on semantic versioning and conventional commits"
inputs:
  command:
    description: "The release-plz command to run. Accepted values: `release-pr`, `release`. If unspecified, this action runs both these commands."
    required: false
  registry:
    description: "Registry where the packages are stored. The registry name needs to be present in the Cargo config. If unspecified, crates.io is used."
    required: false
  update_dependencies:
    description: "If `true`, update all the dependencies in the Cargo.lock file by running `cargo update`. If `false`, only update the workspace packages by running `cargo update --workspace`. (Default: `false`)."
    default: "false"
    required: false
  no_changelog:
    description: "Don't create/update changelog. (Default: `false`)."
    default: "false"
    required: false
  project_manifest:
    description: "Path to the Cargo.toml of the project you want to update. If not provided, release-plz will use the Cargo.toml of the
            root directory. Both Cargo workspaces and single packages are supported."
    required: false
  changelog_config:
    description: "Path to the git cliff configuration file. Defaults to the `keep a changelog` configuration."
    required: false
  git_release:
    description: "Publish the GitHub release for the created git tag. (Default: `true`)."
    default: "true"
    required: false
  version:
    description: "Release-plz version to use. It must be an existing git tag name. For example `release-plz-v0.2.45`. (Default: `latest`)."
    default: "release-plz-v0.2.53"
    required: false
branding:
  icon: "zap"
  color: "yellow"
runs:
  using: "composite"
  steps:
    - run: echo "downloading release-plz".
      shell: bash
    - name: Install cargo-semver-checks
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with:
        repo: obi1kenobi/cargo-semver-checks
        tag: v0.18.3
        cache: enable
    - name: Install release-plz
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with:
        repo: MarcoIeni/release-plz
        tag: ${{ inputs.version }}
        cache: enable
    - run: |
        if [[ "${{ inputs.no_changelog }}" != "false" ]]
        then
            echo "do not generate changelog."
            NO_CHANGELOG="--no-changelog"
        else
            NO_CHANGELOG=""
        fi

        if [[ "${{ inputs.update_dependencies }}" != "false" ]]
        then
            echo "Update all dependencies."
            UPDATE_DEPENDENCIES="--update-dependencies"
        else
            UPDATE_DEPENDENCIES=""
        fi

        if [[ "${{ inputs.git_release }}" == "true" ]]
        then
            GIT_RELEASE="--git-release --git-token ${GITHUB_TOKEN}"
        else
            echo "Git release disabled."
            GIT_RELEASE=""
        fi

        if [[ -n "${{ inputs.registry }}" ]]
        then
            echo "using registry '${{ inputs.registry }}'"
            ALT_REGISTRY="--registry ${{ inputs.registry }}"
        else
            ALT_REGISTRY=""
        fi

        if [[ -n "${{ inputs.project_manifest }}" ]]
        then
            echo "using project manifest '${{ inputs.project_manifest }}'"
            PROJECT_MANIFEST="--project-manifest ${{ inputs.project_manifest }}"
        else
            PROJECT_MANIFEST=""
        fi

        if [[ -n "${{ inputs.changelog_config }}" ]]
        then
            echo "using changelog config '${{ inputs.changelog_config }}'"
            CHANGELOG_CONFIG="--changelog-config ${{ inputs.changelog_config }}"
        else
            CHANGELOG_CONFIG=""
        fi

        git config --global user.email "release-plz@github.com"
        git config --global user.name "release-plz"

        if [[ -z "${{ inputs.command }}" || "${{ inputs.command }}" == "release-pr" ]]
        then
        echo "-- Running release-plz release-pr --"
        release-plz release-pr\
            --git-token ${GITHUB_TOKEN}\
            --repo-url https://github.com/${GITHUB_REPOSITORY}\
            ${NO_CHANGELOG}\
            ${UPDATE_DEPENDENCIES}\
            ${ALT_REGISTRY}\
            ${PROJECT_MANIFEST}\
            ${CHANGELOG_CONFIG}
        fi

        if [[ -z "${{ inputs.command }}" || "${{ inputs.command }}" == "release" ]]
        then
        echo "-- Running release-plz release --"
        release-plz release\
            ${ALT_REGISTRY}\
            ${PROJECT_MANIFEST}\
            ${CHANGELOG_CONFIG}\
            ${GIT_RELEASE}
        fi
      shell: bash
