name: Test

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create test project
        run: |
          cd .github/workflows/
          cargo new marco-test-one
          cd marco-test-one
          git init
          git add .
          git commit -m "first commit"
      - name: Run release-plz
        uses: ./ # Uses an action in the root directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_LOG: trace
        with:
          project_manifest: .github/workflows/marco-test-one/Cargo.toml
